config/routes.rb
AlertiTest::Application.routes.draw do

  resources :articles, except: [:edit, :update]
  resources :comments, only: :create
  resources :sessions, only: [:new, :create, :destroy], path_names: { new: 'sign_in', destroy: 'sign_out' }

  namespace :admin do
    resources :comments_moderations, only: [:index, :create]
  end

  root to: 'articles#index'

end

app/models/article.rb
class Article
  include Whenua::Entity
  extend ActiveModel::Naming # FIXME : Alreadi present in Entity. Find why it is necessary to include it here again

  attribute :content,     String
  attribute :title,       String
  attribute :user_id,     Integer
  attribute :username,    String

  # validates :title,    presence: true
  # validates :content,  presence: true
  # validates :user_id,  presence: true
  # validates :username, presence: true

  def user=(user)
    self.user_id  = user.id
    self.username = user.username
  end

end

app/models/comment.rb
class Comment
  include Virtus
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend  ActiveModel::Naming

  attr_reader :id

  attribute :article_id,  Integer
  attribute :content,     String
  attribute :created_at,  String  # TODO : Implement custom serialization and remove it from attributes
  attribute :type,        String  # TODO : Implement custom serialization and remove it from attributes
  attribute :updated_at,  String  # TODO : Implement custom serialization and remove it from attributes
  attribute :user_id,     Integer
  attribute :username,    String
  attribute :moderation,  Integer


  validates :article_id,  presence: true
  validates :content,     presence: true
  validates :user_id,     presence: true
  validates :username,    presence: true

  def moderate(value)
    self.moderation = value
  end

  def persisted?
    id.present?
  end

  def touch
    now         = Time.now.utc
    @created_at = now if @created_at.nil?
    @updated_at = now
  end

  def type
    self.class.name.downcase
  end

  def user=(user)
    self.user_id  = user.id
    self.username = user.username
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  attr_accessor :password_confirmation

  attr_accessible :username, :email, :password, :password_confirmation

  validates :username,              presence:   true,
                                    uniqueness: true

  validates :email,                 presence:   true,
                                    uniqueness: true

  validates :password,              presence:     true,
                                    confirmation: true

  validates :password_confirmation, presence: true


  def admin?
    self.admin
  end

end

app/controllers/admin/admin_controller.rb
# encoding: utf-8

module Admin
  class AdminController < ApplicationController
    before_filter :require_admin

    protected

    def require_admin
      require_login

      unless current_user.admin?
        redirect_to root_path, alert: "Vous n'êtes pas autorisé à accéder à cette partie de l'application"
      end
    end

  end
end

app/controllers/admin/comments_moderations_controller.rb
# encoding: utf-8

module Admin
  class CommentsModerationsController < AdminController

    def index
      page   = (params[:page] || 1)
      unless params[:filter]
        params[:filter] = {moderation: 0}
      end

      @article             = ShowArticle.new.do(params[:id])
      @comments            = ListPendingCommentsForArticle.new(current_user, page).do(params[:id], params[:filter][:moderation])

      @total_count         = ListPendingCommentsForArticle.new(current_user, page).do(params[:id], 0).comments.total_rows
      @not_moderated_count = ListPendingCommentsForArticle.new(current_user, page).do(params[:id], 1).comments.total_rows
      @positive_count      = ListPendingCommentsForArticle.new(current_user, page).do(params[:id], 3).comments.total_rows
      @negative_count      = ListPendingCommentsForArticle.new(current_user, page).do(params[:id], 4).comments.total_rows
      @neutral_count       = ListPendingCommentsForArticle.new(current_user, page).do(params[:id], 5).comments.total_rows

    end

    def create
      comment_id       = params[:id]
      moderation_value = params[:value]

      @comment = ModerateComment.new(current_user).do(comment_id, moderation_value)
      redirect_to action: :index, id: @comment.comment.article_id
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

protected

  def not_authenticated
    redirect_to new_session_path, alert: "Vous devez d'abord vous connecter"
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :require_login, only: [:new, :create, :delete]

  def index
    @rcount = CountTotalArticles.new.do
    @rm = ListLastArticles.new.do
  end

  def new
    @rm = NewArticle.new.do
  end

  def create
    @rm = CreateArticle.new.do(params[:article], current_user)
    @rm.success? ? redirect_to(articles_path) : render(:new)
  end

  def show
    @rm  = ShowArticle.new.do(params[:id])
    @cm  = NewComment.new(params[:id]).do
    @csm = ListCommentsForArticle.new().do(params[:id])
  end

  def destroy
    DeleteArticle.new.do(params[:id])
    redirect_to action: :index
  end

end

app/controllers/comments_controller.rb
# encoding: utf-8

class CommentsController < ApplicationController
  before_filter :require_login, only: [:create]

  def create
    @rm = CreateComment.new(current_user).exec(params[:comment])

    flash[:error] = "Votre commentaire n'a pas été ajouté" unless @rm.success?
    redirect_to(article_path(params[:comment][:article_id]))
  end

  def show
    @rm = Articles::ShowArticle.new.exec(params[:id])
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController

  def new
    @rm = UserRegistration.new.new_user
  end


  def create
    @rm = UserRegistration.new.register(params[:user])
    @rm.success? ? redirect_to(root_path) : render(:new)
  end

end

app/controllers/sessions_controller.rb
# encoding: utf-8

class SessionsController < ApplicationController


  def new

  end

  def create
    rm = UserAuthentication.new.authenticate(params[:credentials][:login], params[:credentials][:password])

    if rm.success?
      auto_login rm.user
      redirect_back_or_to(:root, notice: 'Vous êtes maintenant connecté.')
    else
      flash.now[:alert] = "Authentification échouée." # TODO : Message should not be set in plain text here
      render(:new)
    end
  end

  def destroy
    logout
    redirect_to root_path, notice: 'Vous êtes maintenant déconnecté.'
  end

end

app/helpers/application_helper.rb
# encoding: utf-8
module ApplicationHelper

  def format_time(time)
    time.strftime("le %m/%d/%Y à %H:%M")
  end

end

app/views/admin/comments_moderations/index.html.slim
- content_for :heading
  h1
    'Commentaires à modérer pour l'article :
    small = link_to @article.article.title, article_path(@article.article.id)

= simple_form_for :filter, method: :get, url: admin_comments_moderations_path do |form|
  = hidden_field_tag :id, @article.article.id
  = form.input :moderation, label: 'Filtrer par', as: :select, include_blank: false, collection: {'tous' => 0, 'non modérés' => 1, 'modérés' => 2, 'positifs' => 3, 'négatifs' => 4, 'neutres' => 5}, selected: params[:filter][:moderation]
  = form.submit 'Filtrer'

br

= paginate @comments.comments

- @comments.comments.each do |comment|

  p = comment['content']
  span
    | Posté :&nbsp;
    = comment['created_at']
    | &nbsp; par &nbsp;
  strong = comment['username']
  | &nbsp; Statut: &nbsp;
  = comment['moderation']
  br
  = link_to 'Négative', admin_comments_moderations_path(id: comment['id'], value: -1), method: :post
  br
  = link_to 'Neutre', admin_comments_moderations_path(id: comment['id'], value: 0), method: :post
  br
  = link_to 'Positive', admin_comments_moderations_path(id: comment['id'], value: 1), method: :post
  hr

= paginate @comments.comments

app/views/articles/_list_article.slim
article
  h3
    = link_to article.title, article_path(article.id)
  h6
    'Rédigé par
    em
      = article.username
    '
    = format_time article.created_at
  .row
    .large-12.columns
      p
        = article.content.truncate 250

  - if current_user
    .right
      = link_to 'Supprimer', article_path(article.id), method: :delete, confirm: 'Etes vous sûr ?', class: 'tiny button'

app/views/articles/index.html.slim
- content_for :side_content do
  h5
    | Total des articles
  br
  = @rcount.count

-content_for :heading do
  .large-6.columns
    h1
      | Derniers articles
  .right
    = link_to 'Rédiger un article', new_article_path, class: 'button success'


- @rm.articles.each_with_index do |article, i|
  = render 'list_article', article: article
  - if i < (@rm.articles.length - 1)
    hr

app/views/articles/new.html.slim
h1 Nouvel article

= simple_form_for @rm.article, url: articles_path do |form|
  = form.input :title
  = form.input :content, as: :text
  = form.submit

app/views/articles/show.html.slim
- content_for :heading
  h1 = @rm.article.title

p = @rm.article.content


- if logged_in?

  h2 Commentez

  = simple_form_for @cm.comment do |form|
    = form.input :article_id, as: :hidden
    = form.input :content, as: :text, label: false
    = form.submit 'Envoyer', class: 'button success right'

hr

h2.large-7.columns Commentaires

- if logged_in? && current_user.admin?
  = link_to 'Modérer les commentaires', admin_comments_moderations_path(id: @rm.article.id), class: 'button right'

- @csm.comments.each do |comment|
  strong
    = comment.username
  p
    = comment.content
  hr

app/views/layouts/application.html.slim
doctype
html
  head
    title AlertiTest
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  body
    .row
      .large-12.columns
        nav.top-bar
          ul.title-area
            li.name
              h1 = link_to 'Alerti', root_path

          section.top-bar-section
            ul.right
              - unless current_user
                li
                  = link_to 'Connexion', new_session_path
              - else
                li
                  a
                    ' Bonjour
                    = current_user.username
                li.divider
                li
                  = link_to 'Déconnexion', session_path(current_user), method: :delete

    .row
      .large-12.columns
        - if notice
          .alert-box.success data-alert=''
            = notice
            a.close href="#" &times;
        - if alert
          .alert-box.alert = alert
            a.close href="#" &times;

    .row
      .large-12.columns role="heading"
        = yield :heading
      hr

    .row
      .large-9.columns
        = yield

      aside.large-3.columns
        .panel
          = yield :side_content

    footer.row
      .large-12.columns
        hr
        .row
          .large-6.columns
            p &copy; Wengee